# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-simplemahjong

# >> macros
# << macros

Summary:    Simple Mahjong
Version:    1.1
Release:    1
Group:      Qt/Qt
License:    GPLv3
URL:        http://poetaster.de
Source0:    %{name}-%{version}.tar.bz2
Requires:   libsailfishapp-launcher
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
%description
a simple mahjong tile solitaire, via guhoffman's fork of the original green mahjong

%if "%{?vendor}" == "chum"
PackageName: Simple Mahjong
Type: desktop-application
Categories:
 - Game
DeveloperName: Mark Washeim (poetaster)
Custom:
 - Repo: https://github.com/poetaster/harbour-simplemahjong
Icon: https://raw.githubusercontent.com/poetaster/harbour-simplemahjong/master/icons/172x172/harbour-moremahjong.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/harbour-simplemahjong/main/screen-1.jpg
 - https://raw.githubusercontent.com/poetaster/harbour-simplemahjong/main/screen-2.jpg
 - https://raw.githubusercontent.com/poetaster/harbour-simplemahjong/main/screen-3.jpg
Url:
  Homepage: https://github.com/poetaster/harbour-simplemahjong
  Donation: https://www.paypal.me/poetasterFOSS
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
